name: Deploy to SIT

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli
          sf --version

      - name: Authenticate to Salesforce (JWT)
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > server.key
          sf org login jwt \
            --client-id ${{ secrets.SF_CONSUMER_KEY_SIT }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME_SIT }} \
            --alias SIT

      - name: Deploy Metadata to SIT
        run: |
          sf project deploy start \
            --source-dir force-app \
            --target-org SIT